_wandb:
    value:
        cli_version: 0.21.1
        e:
            mbhrvy0x1z2oln2ndcmc17lumoe8w4pr:
                apple:
                    ecpuCores: 6
                    gpuCores: 14
                    memoryGb: 18
                    name: Apple M3 Pro
                    pcpuCores: 5
                    ramTotalBytes: "19327352832"
                    swapTotalBytes: "4294967296"
                args:
                    - -t
                    - Task001_DMRIHCP152
                    - -m
                    - ResNet50
                    - -d
                    - 2D
                cpu_count: 11
                cpu_count_logical: 11
                disk:
                    /:
                        total: "494384795648"
                        used: "473737465856"
                email: timurkatime@gmail.com
                executable: /Users/timur/anaconda3/envs/diffusion-segmentation/bin/python3.12
                host: MacBook-Pro-4.local
                memory:
                    total: "19327352832"
                os: macOS-15.5-arm64-arm-64bit
                program: /Users/timur/anaconda3/envs/diffusion-segmentation/bin/yucca_train
                python: CPython 3.12.2
                root: /Users/timur/Documents/dmri_anomaly_detection_local/yucca_tasks/models/Task001_DMRIHCP152/ResNet50__2D/YuccaManager__YuccaPlanner/default/kfold_5_fold_0/version_0
                startedAt: "2025-08-12T19:40:21.889487Z"
                writerId: mbhrvy0x1z2oln2ndcmc17lumoe8w4pr
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 53
                - 103
                - 106
            "2":
                - 1
                - 5
                - 9
                - 41
                - 48
                - 49
                - 53
                - 63
                - 103
                - 106
            "3":
                - 7
                - 13
                - 66
            "4": 3.12.2
            "5": 0.21.1
            "12": 0.21.1
            "13": darwin-arm64
