_wandb:
    value:
        cli_version: 0.21.1
        e:
            eszfzotfeudk6yivpht5dxpno38baxcg:
                apple:
                    ecpuCores: 6
                    gpuCores: 14
                    memoryGb: 18
                    name: Apple M3 Pro
                    pcpuCores: 5
                    ramTotalBytes: "19327352832"
                args:
                    - -t
                    - Task001_DMRIHCP152
                    - -m
                    - TinyUNet
                    - -d
                    - 2D
                cpu_count: 11
                cpu_count_logical: 11
                disk:
                    /:
                        total: "494384795648"
                        used: "467046170624"
                email: timurkatime@gmail.com
                executable: /Users/timur/anaconda3/envs/diffusion-segmentation/bin/python3.12
                host: MacBook-Pro-4.local
                memory:
                    total: "19327352832"
                os: macOS-15.5-arm64-arm-64bit
                program: /Users/timur/anaconda3/envs/diffusion-segmentation/bin/yucca_train
                python: CPython 3.12.11
                root: /Volumes/TimurDKI/dmri_anomaly_detection/yucca_tasks/models/Task001_DMRIHCP152/TinyUNet__2D/YuccaManager__YuccaPlanner/default/kfold_5_fold_0/version_0
                startedAt: "2025-08-12T15:45:41.800552Z"
                writerId: eszfzotfeudk6yivpht5dxpno38baxcg
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 53
                - 103
                - 106
            "2":
                - 1
                - 5
                - 9
                - 41
                - 48
                - 49
                - 53
                - 63
                - 103
                - 106
            "3":
                - 7
                - 13
                - 66
            "4": 3.12.11
            "5": 0.21.1
            "12": 0.21.1
            "13": darwin-arm64
config:
    value:
        allow_missing_modalities: false
        augmentation_parameters:
            additive_noise_mean:
                - 0
                - 0
            additive_noise_p_per_sample: 0.2
            additive_noise_sigma:
                - 0.001
                - 0.0001
            biasfield_p_per_sample: 0.33
            blurring_p_per_channel: 0.5
            blurring_p_per_sample: 0.2
            blurring_sigma:
                - 0
                - 1
            convert_labels_to_regions: false
            copy_image_to_label: true
            cval: min
            deep_supervision: false
            do_tube: false
            elastic_deform_alpha:
                - 200
                - 600
            elastic_deform_p_per_sample: 0.33
            elastic_deform_sigma:
                - 20
                - 30
            gamma_p_invert_image: 0.05
            gamma_p_per_sample: 0.2
            gamma_range:
                - 0.5
                - 2
            gibbs_ringing_axes:
                - 0
                - 2
            gibbs_ringing_cut_freq:
                - 96
                - 129
            gibbs_ringing_p_per_sample: 0.2
            label_dtype: builtins.int
            mask_image_for_reconstruction: true
            mask_ratio: 0.5
            mirror_axes:
                - 0
                - 1
            mirror_p_per_axis: 0.33
            mirror_p_per_sample: 0
            motion_ghosting_alpha:
                - 0.85
                - 0.95
            motion_ghosting_axes:
                - 0
                - 2
            motion_ghosting_num_reps:
                - 2
                - 11
            motion_ghosting_p_per_sample: 0.2
            multiplicative_noise_mean:
                - 0
                - 0
            multiplicative_noise_p_per_sample: 0.2
            multiplicative_noise_sigma:
                - 0.001
                - 0.0001
            patch_size:
                - 128
                - 96
            pre_aug_patch_size:
                - 160
                - 160
            random_crop: false
            rotation_p_per_axis: 0.66
            rotation_p_per_sample: 0.2
            rotation_x:
                - -30
                - 30
            rotation_y:
                - -0
                - 0
            rotation_z:
                - -0
                - 0
            scale_factor:
                - 0.9
                - 1.1
            scale_p_per_sample: 0.2
            simulate_lowres_p_per_axis: 0.33
            simulate_lowres_p_per_channel: 0.5
            simulate_lowres_p_per_sample: 0.2
            simulate_lowres_zoom_range:
                - 0.5
                - 1
            skeleton: false
            skip_label: true
        base_experiment: default
        batch_size: 512
        ckpt_patch_size: null
        ckpt_path: null
        ckpt_plans: null
        ckpt_seed: null
        ckpt_version_dir: null
        ckpt_wandb_id: null
        continue_from_most_recent: true
        experiment: default
        image_extension: nii.gz
        labels: null
        manager_name: YuccaManager
        model_dimensions: 2D
        model_name: TinyUNet
        num_classes: 1
        num_modalities: 1
        patch_based_training: true
        patch_size:
            - 128
            - 96
        planner_name: YuccaPlanner
        plans:
            allow_missing_modalities: false
            crop_to_nonzero: true
            dataset_properties:
                background_pixel_values:
                    - 0
                classes: []
                data_dimensions: 3
                image_extension: nii.gz
                intensities:
                    - max: 0.1174204871058464
                      maxmin: 3.3843702840208323e-10
                      mean: 0.0006542730843648314
                      min: 3.322259134463934e-10
                      percentile_00_5: 3.3225121445767945e-10
                      percentile_99_5: 0.0021426064142025993
                      std: 0.0002813520550262183
                labels: null
                modalities:
                    "0": MD
                original_max_size:
                    - 145
                    - 174
                    - 145
                original_max_spacing:
                    - 1.25
                    - 1.25
                    - 1.25
                original_median_size:
                    - 145
                    - 174
                    - 145
                original_median_spacing:
                    - 1.25
                    - 1.25
                    - 1.25
                original_min_size:
                    - 145
                    - 174
                    - 145
                original_min_spacing:
                    - 1.25
                    - 1.25
                    - 1.25
                regions: null
            keep_aspect_ratio_when_using_target_size: true
            max_cc_size: 0
            max_n_cc: 0
            mean_cc_size: 0
            mean_n_cc: 0
            min_cc_size: 0
            min_n_cc: 0
            new_max_size:
                - 122
                - 158
                - 118
            new_mean_size:
                - 110
                - 142
                - 110
            new_min_size:
                - 100
                - 130
                - 103
            normalization_scheme:
                - standardize
            num_classes: 0
            num_modalities: 1
            plans_name: YuccaPlanner
            preprocessor: UnsupervisedPreprocessor
            suggested_dimensionality: 3D
            target_coordinate_system: RAS
            target_size: null
            target_spacing:
                - 1.25
                - 1.25
                - 1.25
            task_type: self-supervised
            transpose_backward:
                - 0
                - 1
                - 2
            transpose_forward:
                - 0
                - 1
                - 2
        plans_path: /Volumes/TimurDKI/dmri_anomaly_detection/yucca_tasks/preprocessed/Task001_DMRIHCP152/YuccaPlanner/YuccaPlanner_plans.json
        regions: null
        save_dir: /Volumes/TimurDKI/dmri_anomaly_detection/yucca_tasks/models/Task001_DMRIHCP152/TinyUNet__2D/YuccaManager__YuccaPlanner/default/kfold_5_fold_0
        seed: 812174541
        split_idx: 0
        split_method: kfold
        split_param: 5
        task: Task001_DMRIHCP152
        task_type: self-supervised
        train_data_dir: /Volumes/TimurDKI/dmri_anomaly_detection/yucca_tasks/preprocessed/Task001_DMRIHCP152/YuccaPlanner
        use_label_regions: false
        version: 0
        version_dir: /Volumes/TimurDKI/dmri_anomaly_detection/yucca_tasks/models/Task001_DMRIHCP152/TinyUNet__2D/YuccaManager__YuccaPlanner/default/kfold_5_fold_0/version_0
        wandb_id: 2zc29mfg
crop_to_nonzero:
    value: true
deep_supervision:
    value: false
disable_inference_preprocessing:
    value: false
hparams_path:
    value: /Volumes/TimurDKI/dmri_anomaly_detection/yucca_tasks/preprocessed/Task001_DMRIHCP152/YuccaPlanner/YuccaPlanner_plans.json
log_image_every_n_epochs:
    value: null
loss_kwargs:
    value:
        soft_dice_kwargs:
            apply_softmax: true
lr_scheduler_kwargs:
    value:
        eta_min: 1e-09
model_dimensions:
    value: 2D
num_classes:
    value: 1
num_modalities:
    value: 1
optimizer_kwargs:
    value:
        lr: 0.001
        momentum: 0.9
patch_size:
    value:
        - 128
        - 96
progress_bar:
    value: false
sliding_window_overlap:
    value: 0.5
sliding_window_prediction:
    value: true
step_logging:
    value: false
test_time_augmentation:
    value: false
transpose_backward:
    value:
        - 0
        - 1
        - 2
transpose_forward:
    value:
        - 0
        - 1
        - 2
