compile_mode: null
config:
  allow_missing_modalities: false
  base_experiment: base_experiment
  batch_size: 8
  ckpt_patch_size: null
  ckpt_path: null
  ckpt_seed: null
  ckpt_version_dir: null
  ckpt_wandb_id: null
  continue_from_most_recent: true
  experiment: base_experiment
  image_extension: nii.gz
  manager_name: AMAES
  model_dimensions: 3D
  model_name: unet_b
  num_classes: 1
  num_modalities: 1
  patch_based_training: true
  patch_size: &id001 !!python/tuple
  - 128
  - 128
  - 128
  planner_name: YuccaPlanner
  plans_path: /Volumes/TimurDKI/dmri_anomaly_detection/yucca_tasks/preprocessed/Task001_DMRIHCP152/YuccaPlanner/YuccaPlanner_plans.json
  precision: bf16-mixed
  regions_in_order: null
  regions_labeled: null
  save_dir: /Volumes/TimurDKI/dmri_anomaly_detection/yucca_tasks/models/Task001_DMRIHCP152/unet_b
  seed: 812170230
  split_idx: 0
  split_method: simple_train_val_split
  split_param: 0.01
  task: Task001_DMRIHCP152
  task_type: self-supervised
  train_data_dir: /Volumes/TimurDKI/dmri_anomaly_detection/yucca_tasks/preprocessed/Task001_DMRIHCP152/YuccaPlanner
  use_label_regions: false
  version: 0
  version_dir: /Volumes/TimurDKI/dmri_anomaly_detection/yucca_tasks/models/Task001_DMRIHCP152/unet_b/versions/version_0
cosine_period_ratio: 1
debug_losses: false
epochs: 100
input_channels: 1
learning_rate: 0.0001
mask_ratio: 0.6
model_name: unet_b
norm_type: null
num_classes: 1
optimizer: AdamW
patch_size: *id001
rec_loss_masked_only: false
should_compile: false
steps_per_epoch: 17
token_size: 4
warmup_epochs: 5
